# Generated by Django 5.2.3 on 2025-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(upload_to='food-images/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
