# Generated by Django 5.2.3 on 2025-09-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebaseUser', '0002_firebaseuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
